Use `aerich` for database migrations
dipdup-io/dipdup pull request #1110
Opened 2024-09-29 03:24 UTC by bigherc18

2024-09-30 21:07 UTC, droserasprout commented on src/dipdup/cli.py
> +from aerich.cli import cli as aerich_cli
This import should be lazy, since it takes 0.6s and  `dipdup.cli` module is imported for every command.

2024-09-30 21:34 UTC, droserasprout requested changes
Hi! Thanks for your contribution! It's a great code with many smart solutions; I like every piece of it! My only concern is making this integration optional in every way: dependencies, imports, files in the project package.

2024-09-30 21:34 UTC, droserasprout commented on src/dipdup/cli.py
> +from aerich.cli import cli as aerich_cli
This import should be lazy, since it takes 0.6s and dipdup.cli module is imported for every command.

2024-09-30 21:34 UTC, droserasprout commented on src/dipdup/cli.py
> +    from dipdup.aerich import create_aerich_command
This import is not lazy enough. You could do it right before the call.

2024-09-30 21:34 UTC, droserasprout commented on src/dipdup/config/__init__.py
> +    :param migrations_dir: Where to store migrations files (relative to project root)
I suggest removing an ability to configure this path and hardcode it in `DipDupPackage` class instead (but don't create by default). We already use fixed directory paths for every other section; it makes things much simpler to maintain.

2024-09-30 21:34 UTC, droserasprout commented on pyproject.toml
> +    "aerich~=0.7.2",
Let's make this dependency optional. A majority of users don't need migrations, and dependency tree is already very bloated. If it's not installed -- just ignore the whole migrations part.

2024-09-30 21:34 UTC, droserasprout commented on src/dipdup/cli.py
> +schema.add_command(aerich_cli.commands['history'])
Please wrap this with try except to silently fail when aerich is not installed.

2024-10-01 14:00 UTC, bigherc18 commented
Do you guys prefer `rebase` or `merge` with `next` to fix the conflicts ?

2024-10-01 14:52 UTC, droserasprout commented
@bigherc18 We squash every merge request, so it's up to you what's inside.

2024-10-01 14:59 UTC, bigherc18 commented
I have some concerns and limitations:

- `aerich` will be confused if the user changes the database. If we want to support changing the database, we have to make aerich aware of which database is being used.
- If you answer "No" to the question "Downgrade is dangerous, which may cause data loss. Are you sure? [y/N]" after running `dipdup schema downgrade`, the CLI hangs there forever.
- `aerich` has confusing messages after running `heads` and `history`. It makes the user feel like they have to take action when everything is actually fine: "No available heads, try migrate first."

2024-10-01 18:13 UTC, droserasprout requested changes
Your last comment shows such a great amount of testing done! 🥰 I think, there's nothing critical. Yes, running commands in random order on multiple databases sometimes confuse aerich, but all real cases works perfectly.

I have just a few nitpicks. Then make sure that `make all docs` command passes, add yourself to the `thanks.md` file, and let's merge it!

2024-10-01 18:13 UTC, droserasprout commented on .vscode/settings.json
> +    },
Please, remove this part.

2024-10-01 18:13 UTC, droserasprout commented on src/dipdup/database.py
> +        'models': ['dipdup.models'],
This line is a duplicate. Without it mypy seems to be okay with `model_modules['models'] = [models]`

2024-10-01 18:13 UTC, droserasprout commented on src/dipdup/cli.py
> +                f"""Database migrations is not initialize at {migrations_dir}.
*are not initialized

2024-10-01 18:13 UTC, droserasprout commented on src/dipdup/cli.py
> +            raise click.Abort()
Please, raise `dipdup.exceptions.ProjectPackageError` here so we get a nicer help message.

2024-10-02 00:11 UTC, bigherc18 commented
> I think, there's nothing critical. Yes, running commands in random order on multiple databases sometimes confuse aerich, but all real cases works perfectly.

Thank you for your feedback but I just want to make sure I explained my concerns clear enough for you

1. Multiple databases not supported by migrations

TLDR; if a user uses multiple databases at the same time, migrations is not supported

I see dipdup makes it easy for users to swap databases by just combining different config files with multiple `-c` args, the problem is: if a user swaps his database after doing some migrations in the first one, `aerich` is now really confused and I don't even know what will happen, the `aerich` table will be empty (or contains migrations history for the second database) but the `migrations` folder still contains files from the first database

I think this worth at least a note in the docs 

3. CLI handing

Here's a little video demonstrating the issue:

![demo](https://github.com/user-attachments/assets/fbf0f9e1-3daf-450f-a575-37af993aefe8)

2024-10-02 16:17 UTC, droserasprout approved these changes

2024-10-02 16:19 UTC, merged