Cache latest release from GitHub for version check in xdg_shared_dir #1095
dipdup-io/dipdup pull request #1113
Opened 2024-09-30 17:06 UTC by MrRoudyk

### Optimize Version Check with Caching

**Summary:**
Enhances version checking by adding a caching mechanism, reducing dependency on real-time GitHub API calls.

**Changes:**

- **Caching Implementation:**
  - Introduced `get_cached_version`, `read_cached_version`, and `write_cached_version` functions.
  - Stores cached version in `latest_version.json` with a 24-hour TTL.

- **Optimized `_check_version`:**
  - Retrieves version from cache first.
  - Queries GitHub API only if cache is missing or expired.

**Notes:**

- Requires the `appdirs` library.

**Known Issues:**

- The issue with `aiohttp` and `fire_and_forget` is not yet resolved.

**Closes #1095 **

2024-09-30 20:37 UTC, droserasprout requested changes

2024-09-30 20:37 UTC, droserasprout commented on src/dipdup/cli.py
> +def _warn_if_outdated(_skip_msg: str, latest_version: str) -> None:
Argument name starting with underscore usually means that it's not used in the function body.	Please, rename the argument.

2024-09-30 20:37 UTC, droserasprout commented on src/dipdup/cli.py
> +async def read_cached_version(cache_file: Path) -> str | None:
This function doesn't contain async calls and can be synchronous.

2024-09-30 20:37 UTC, droserasprout commented on src/dipdup/cli.py
> +async def get_cached_version(cache_file: Path, ttl: int = 86400) -> str | None:
This function doesn't contain async calls and can be synchronous.

2024-09-30 20:37 UTC, droserasprout commented on src/dipdup/cli.py
> +async def write_cached_version(cache_dir: Path, cache_file: Path, latest_version: str) -> None:
This function doesn't contain async calls and can be synchronous.

2024-09-30 20:37 UTC, droserasprout commented on src/dipdup/cli.py
> +        import json
Please, use `orjson` library for handling JSON.

2024-09-30 20:37 UTC, droserasprout commented on src/dipdup/cli.py
> +        if latest_version:
This check is always True.

2024-09-30 20:37 UTC, droserasprout commented on src/dipdup/cli.py
I've spent some time trying to solve #1114, and it's some advanced asyncio magic I currently have no time for. So, let's await `_check_version` immediately. It won't take long since response is cached now.

2024-09-30 20:37 UTC, droserasprout commented on src/dipdup/cli.py
> +    latest_version = await get_cached_version(cache_file)
Installed DipDup version should be cached too so we can invalidate cache later when package will be updated.

2024-09-30 21:00 UTC, bruhhgnik commented
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/dipdup).

### My background and how it can be leveraged
I have experience with Python development and ML models in general.

### How I plan on tackling this issue
Start by implementing functions to cache the latest version in a JSON file with a 24-hour TTL. 
I would modify the existing version check to retrieve the version from cacche first, only querying GitHub if the cache is missing or expired. I would use the appdirs library to manage the storage location for cross-platform compatibility.

2024-09-30 22:23 UTC, Kaminar-i commented
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/dipdup).

### My background and how it can be leveraged
hello i would love to work on this issue

### How I plan on tackling this issue
please kindly assign

2024-10-01 12:38 UTC, estherbreath commented
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/dipdup).

### My background and how it can be leveraged
I am a full-stack developer, and would leverage on my background to; 
    1. Implementing front-end optimizations like client-side caching and UI improvements
    2. Optimizing back-end services with server-side caching and API enhancements 
    3. Utilizing DevOps practices for infrastructure scaling and monitoring 
    4. Ensuring thorough testing and quality assurance across all layers 


### How I plan on tackling this issue
I will take these few steps by way of summary to work on this issue within the possible 
 limited time.

Add caching functions
Store cached version with a 24-hour TTL
Optimize Version Checking by modifying the check version to;
        ◦ Retrieve version from cache 
        ◦ Query GitHub API only if cache is missing or expired 
Investigate and resolve the problem with aiohttp and fire_and_forget

2024-10-01 12:39 UTC, MrRoudyk commented
@droserasprout Thank you for the feedback! I have made all the changes you suggested. Please take a look at the updated code.

2024-10-01 13:01 UTC, droserasprout commented
Great, thanks!

2024-10-01 13:02 UTC, merged

2024-10-01 22:52 UTC, akintewe commented
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/dipdup).

### My background and how it can be leveraged
I'm a CS major with a lot of Python experience, and I've worked on a lot of projects that involved caching systems, performance optimisations, and API integrations. My expertise in software engineering best practices and principles allows me to tackle challenging issues like this one with effectiveness and maintainability.


### How I plan on tackling this issue
I would first analyse the current version checking system and determine the best places to include the cache before implementing caching for the latest release version check. I would create a caching system with read and write functions and a 24-hour TTL, storing the version information in a platform-appropriate location using the appdirs library. The _check_version method would be changed to only call the GitHub API when absolutely necessary, instead of always attempting to retrieve the version from cache. I would see to it that the process's error handling and logging are done correctly. Testing would include misses, expirations, and cache hits, among other scenarios. Lastly, if the caching implementation is impacted by any possible issues with aiohttp and fire_and_forget, I would solve them.